Udate app name `adaptiv_web_settings_dashboard`
Resolves this error that stopped developement for several days:
https://www.odoo.com/mail/view?model=project.task&res_id=1886468
```
Hello Dion,
Thank you for you patience while we were working at this.
The traceback that you are  seeing "The ID "%s" refers to an uninstalled module""" % (xml_id,)
AssertionError: The ID "web_settings_dashboard.web_dashboard_menu" refers to an uninstalled module" is originated form custom application app_menu_setting https://github.com/xaasutility/test/blob/master/app_menu_setting/view/app_setting.xml#L15  this application depends on other module named web_settings_dashboard and making reference to an record created in that application wit the code web_settings_dashboard_action. Now I looked further and and you don't have application depend application "web_settings_dashboard" but you have similar named application "adaptiv_web_settings_dashboard" but no where in the code the record in declared (https://github.com/xaasutility/test/search?q=web_settings_dashboard_action&unscoped_q=web_settings_dashboard_action). Also it looks are all the modules are not tested well during development and you might see more error related to third party apps once you get above error fixed
Unfortunately this is issues related to customized  application I wont be able to help you further as I do not have understanding toe all the application and  this third part app support is not covered with standard support. I will advise you to reach out to the app vendor and for the solution.
Bests
Sent by Odoo S.A. using Odoo.
```